require "rake"
require "albacore"

require "rake-settings"
require "rake-filesystem"
require "rake-nuget"
require "rake-msbuild"
require "rake-dotcover"
require "rake-signtool"
require "rake-innosetup"
require "rake-sonar"
require "rake-nodejs"
require "rake-karma"
require "rake-jslint"
require "rake-plato"
